__file__ requires quotes
error when run with python 3.5.3 on Raspberry Pi

Traceback (most recent call last):
  file "/home/pi/Pimoroni/pianohat/examples/simple-piano.py", line 17, in <module>
    BANK = os.path.join(os.path.dirname(__file__), "sounds")
NameError: name '__file__' is not defined.

MNR note: this is fixed by quoting __file__, as noted in new branch

see https://stackoverflow.com/questions/16771894/python-nameerror-global-name-file-is-not-defined